Repository LaurierHawkHacks/Landing, pull requests merged in 2024-03, with the labels that each got.

#112 Feature: create meet the team section
  src/assets/team/clouds.svg
  src/assets/team/meet-the-team-balloon-banner.svg
  src/assets/team/meet-the-team-building-left.svg
  src/assets/team/meet-the-team-building-right.svg
  src/components/index.tsx
  src/components/sections/Team.section.tsx
  src/index.css
  src/pages/Landing.tsx
Labels: enhancement

#122 Feature: move dashboard button to landing
  package.json
  pnpm-lock.yaml
  src/components/Button/Button.styles.ts
  src/components/Button/Button.test.tsx
  src/components/Button/Button.tsx
  src/components/Navbar/NavItems.tsx
  src/components/Navbar/Navbar.tsx
  src/components/index.tsx
  src/index.css
  tailwind.config.mjs
  tsconfig.json
  vite.config.ts
Labels: enhancement

#125 Fix: update the color
  src/components/Navbar/Menu.tsx
  src/components/Navbar/NavItems.tsx
  src/components/Navbar/Navbar.tsx
Labels: bug

#116 Feature: make hero section prototype
  src/assets/hero/bg-desktop-svg.tsx
  src/assets/hero/bg-mobile-svg.tsx
  src/assets/hero/desktop.svg
  src/assets/hero/mobile.svg
  src/assets/index.tsx
  src/components/index.tsx
  src/components/sections/Hero.section.tsx
  src/index.css
  src/pages/Landing.tsx
Labels: enhancement

#119 Feature/94/create about section
  src/assets/about/about-air-balloon.svg
  src/assets/about/about-section-desktop.svg
  src/assets/about/about-section-mobile.svg
  src/components/index.tsx
  src/components/sections/About.section.tsx
  src/pages/Landing.tsx
  src/pages/index.tsx
Labels: enhancement

#128 Feature/126/update-navbar-links-font-size
  src/components/Navbar/NavItems.tsx
Labels: enhancement

#130 Fix: update the font size for title and subtitle in hero section
  src/components/sections/Hero.section.tsx
Labels: bug

#123 feature/96/faq
  src/assets/background/faqBackground.png
  src/components/Accordion.tsx
  src/components/index.tsx
  src/components/sections/FAQ.section.tsx
  src/pages/Landing.tsx
  tailwind.config.mjs
Labels: enhancement

#142 Feature/133/merge hero section with stats section
  src/assets/about/about-section-desktop.svg
  src/assets/about/about-section-mobile.svg
  src/assets/hero-about/about-air-balloon.svg
  src/assets/hero-about/hero-about-desktop.svg
  src/assets/hero-about/hero-about-mobile.svg
  src/assets/index.tsx
  src/components/index.tsx
  src/components/sections/About.section.tsx
  src/components/sections/Hero.section.tsx
  src/components/sections/HeroStats.section.tsx
  src/pages/Landing.tsx
Labels: enhancement

#143 fix: make profile image circle + increase the subsection heading size
  src/assets/index.tsx
  src/assets/team/meet-the-team-balloon-banner.svg
  src/assets/team/meet-the-team-balloon-banner.webp
  src/components/sections/Team.section.tsx
Labels: bug

#149 Fix: styling in team section
  src/assets/team/meet-the-team-banner.webp
  src/components/index.tsx
  src/components/sections/Team.section.tsx
  src/components/sections/Team/Team.section.tsx
  src/components/sections/Team/data.ts
  src/index.css
Labels: bug, refactor

#151 Fix: update the background in team section
  src/assets/team/meet-the-team-building-right.svg
Labels: bug

#158 Feature/144/add loading animation
  src/assets/hero-about/hero-about-desktop-bak.svg
  src/assets/hero-about/hero-about-mobile-bak.svg
  src/components/LoadingAnimation.tsx
  src/components/index.tsx
  src/pages/Landing.tsx
Labels: enhancement

#164 Style: consistent max-width
  src/components/sections/SponsorFAQ.section.tsx
Labels: Style

#170 Fix: no more distorted birdy
  src/components/sections/Contact.section.tsx
  src/components/sections/SponsorFAQ.section.tsx
Labels: bug, style

#163 Fix: make horizontal padding align across the page
  src/components/Accordion.tsx
  src/components/sections/Contact.section.tsx
  src/components/sections/Footer.section.tsx
  src/components/sections/HeroStats.section.tsx
  src/components/sections/SponsorFAQ.section.tsx
  src/components/sections/Team/Team.section.tsx
Labels: style

#178 Fix: style fix in faq section
  src/assets/background/faqBackground.png
  src/assets/faq/bg-desktop.svg
  src/assets/index.tsx
  src/components/sections/TeamFAQ.section.tsx
Labels: bug, style

#175 Refactor: Make LoadingAnimation conditional
  src/pages/Landing.tsx
Labels: refactor

#173 Fix: good birdy at contact
  src/components/sections/Contact.section.tsx
Labels: bug, style

#185 Fix: remove redundant image in mobile + font size fix
  src/components/sections/HeroStats.section.tsx
Labels: style

#183 Fix: no more overflow in team section
  src/assets/team/meet-the-team-building-right.svg
  src/components/sections/TeamFAQ.section.tsx
Labels: bug, style

#190 Feature/186/get contact us button working
  package.json
  pnpm-lock.yaml
  src/components/sections/Contact.section.tsx
Labels: enhancement

#191 fix: make sure the navbar links are linking to the right places
  src/components/Navbar/NavItems.tsx
  src/components/Navbar/Navbar.tsx
  src/components/sections/Contact.section.tsx
  src/components/sections/HeroStats.section.tsx
  src/components/sections/Sponsor.section.tsx
  src/components/sections/TeamFAQ.section.tsx
  src/index.css
Labels: bug, style

#195 Fix: anchor space fix in contact section
  src/components/Navbar/NavItems.tsx
Labels: bug, style

#202 Fix: update the date in faq tab
  src/components/sections/data/faqData.ts
Labels: bug

#199 Fix: edit dates in stats section
  src/assets/hero-about/hero-about-desktop.svg
  src/components/sections/HeroStats.section.tsx
Labels: bug

#205 fix: background gradient in faq-team section
  src/components/sections/TeamFAQ.section.tsx
Labels: style
