Repository LaurierHawkHacks/Landing, pull requests merged in 2024-04, with the labels that each got.

#211 fix ts errors in sponsor section
  src/components/sections/Sponsor.section.tsx
Labels: enhancement

#218 update sign up for newsletter button
  src/components/sections/Contact.section.tsx
Labels: enhancement

#227 [Update] wait for Desktop and Mobile svg
  src/pages/Landing.tsx
Labels: bug

#236 Feature/231/update-primary-button
  src/components/Button/Button.styles.ts
  src/index.css
Labels: enhancement

#235 Feature/234/reorder-sponsors-section
  src/components/sections/Sponsor.section.tsx
Labels: enhancement

#248 Fix: add more sponsor links
  src/utils/SponsorLinks.tsx
Labels: bug, style

#239 Fix: accessibility issue
  src/components/Navbar/Menu.tsx
  src/components/Navbar/Navbar.tsx
  src/components/index.tsx
  src/components/sections/Sponsor.section.tsx
  src/components/sections/TeamFAQ.section.tsx
  src/index.css
  src/pages/Landing.tsx
Labels: bug

#250 fix: revamp sponsorship
  src/assets/index.tsx
  src/assets/logos/assembly.png
  src/assets/logos/ccubed.png
  src/assets/logos/certopus.png
  src/assets/logos/cisco.png
  src/assets/logos/dcl.png
  src/assets/logos/defiblocks.png
  src/assets/logos/digitalocean.png
  src/assets/logos/distributive.png
  src/assets/logos/dominos.png
  src/assets/logos/echo3d.png
  src/assets/logos/ennios.png
  src/assets/logos/fantuan.png
  src/assets/logos/fdm.png
  src/assets/logos/fintech.png
  src/assets/logos/indofood.png
  src/assets/logos/interviewbuddy.png
  src/assets/logos/interviewcake.png
  src/assets/logos/jdoodle.png
  src/assets/logos/leadingleaders.png
  src/assets/logos/near.png
  src/assets/logos/nibiru.png
  src/assets/logos/ollon.png
  src/assets/logos/roku.png
  src/assets/logos/roomiez.png
  src/assets/logos/rosenfeld.png
  src/assets/logos/smokes.png
  src/assets/logos/soc.png
  src/assets/logos/solana.png
  src/assets/logos/streamyard.png
  src/assets/logos/sweetlous.png
  src/assets/logos/vectara.png
  src/assets/logos/verbwire.png
  src/assets/logos/veritas.png
  src/assets/logos/wolfram.png
  src/components/sections/Sponsor.section.tsx
  src/components/sections/data/index.ts
  src/components/sections/data/sponsorData.ts
  src/utils/SponsorLinks.tsx
  src/utils/index.tsx
Labels: enhancement

#254 fix: center the text in the hero background
  src/assets/hero-about/hero-about-desktop.svg
Labels: style

#259 Fix: hero background
  src/assets/hero-about/hero-about-desktop.svg
Labels: bug

#256 fix: adding more space at sponsors section
  src/components/sections/Sponsor.section.tsx
Labels: style

#262 feat: adding background and spacing at the hero section
  src/components/sections/HeroStats.section.tsx
Labels: enhancement, style

#255 Fix/252/update contact section to match figma
  src/components/sections/Contact.section.tsx
Labels: bug, enhancement

#271 fix: center about section on mobile
  src/components/sections/HeroStats.section.tsx
  src/components/sections/Sponsor.section.tsx
Labels: style

#277 fix: text align center in about us text
  src/components/sections/HeroStats.section.tsx
Labels: style

#273 fix: sponsor's spacing
  src/components/sections/Sponsor.section.tsx
Labels: style

#284 Bug/280/fix faq section issues
  src/components/Accordion.tsx
  src/components/sections/TeamFAQ.section.tsx
  src/components/sections/data/faqData.ts
Labels: bug

#283 Fix: no more / rare content shift
  src/components/sections/HeroStats.section.tsx
  src/index.css
Labels: style

#278 Fix: improve performance
  .github/dependabot.yml
  custom.d.ts
  src/assets/external/mlh-banner.svg
  src/assets/hero-about/hero-about-desktop.svg
  src/assets/hero-about/hero-about-mobile.svg
  src/assets/hero/bg-desktop-svg.tsx
  src/assets/hero/bg-mobile-svg.tsx
  src/assets/hero/desktop.svg
  src/assets/hero/mobile.svg
  src/assets/index.tsx
  src/assets/social-icons.tsx
  src/assets/team/meet-the-team-balloon-banner.webp
  src/components/Accordion.tsx
  src/components/Navbar/Navbar.tsx
  src/components/SocialIcons.tsx
  src/components/sections/Contact.section.tsx
  src/components/sections/HeroStats.section.tsx
  src/components/sections/Sponsor.section.tsx
  src/components/sections/TeamFAQ.section.tsx
  src/index.css
  src/pages/Landing.tsx
  tsconfig.json
Labels: bug

#293 fix: anchor for meet the team has fixed
  src/components/Navbar/NavItems.tsx
  src/components/sections/TeamFAQ.section.tsx
Labels: bug, style

#298 fix: replace the background with correct data
  src/assets/hero-about/hero-about-desktop.svg
  src/assets/hero-about/hero-about-mobile.svg
Labels: bug

#299 fix: improve the accordion transition
  src/components/Accordion.tsx
Labels: bug, style
